services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8081}:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - minio
  postgres:
    image: 'postgres:latest'
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-55403}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
  postgres_data: