spring.application.name=hamix
server.servlet.context-path=/hamix/api/v1

spring.datasource.url=jdbc:postgresql://localhost:5432/hamix
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.user.name=senha
spring.security.user.password=senha


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


