--CREATE SCHEMA IF NOT EXISTS public;

--Album
CREATE TABLE public.album (
    alb_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alb_nome VARCHAR(100) NOT NULL,
    alb_ano VARCHAR(20)
);

--Artista
CREATE TABLE public.artista (
    art_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    art_nome VARCHAR(100) NOT NULL,
    art_origem VARCHAR(100)
);

--N para N
CREATE TABLE public.artista_album (
    art_id INTEGER NOT NULL,
    alb_id INTEGER NOT NULL,
    PRIMARY KEY (art_id, alb_id),
    CONSTRAINT fk_artista_album_artista FOREIGN KEY (art_id)
        REFERENCES public.artista (art_id) ON DELETE CASCADE,
    CONSTRAINT fk_artista_album_album FOREIGN KEY (alb_id)
        REFERENCES public.album (alb_id) ON DELETE CASCADE
);

--Foto
CREATE TABLE public.foto (
    foto_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    url VARCHAR(255),
    alb_id INTEGER NOT NULL,
    CONSTRAINT fk_foto_album FOREIGN KEY (alb_id)
        REFERENCES public.album (alb_id) ON DELETE CASCADE
);
